### ISSUE TITLE
Mukluks allowing frequent sprains...

### ISSUE THREAD

**Issue by JoESmash** [WulfMarius/Ankle-Support#2]
Hello,

I am a fan of the mod because obviously overall sprains have been reduced. However I got frequent and riduculous amounts of sprains while wearing mukluks, which is odd because they are like some of the best boots in the game. Is this intended, or a bug?

**Comment by WulfMarius** [comment]
There are no exceptions or special cases for any type of boots.

Mukluks are certainly one of the warmer boots, but their protection is a rather mediocre 5 - same trial boots. For comparison: Combat Boots have 10 and Ski Boots 12. 
The reduction in sprain is based on the protection value and not on the warmth, so this is probably working as intended (always difficult to judge with randomized events).

**Comment by WulfMarius** [comment]
No further response from the reporter
